# Generated by Django 2.2.6 on 2019-10-21 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travel_buddy_app', '0002_travel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travel',
            name='join',
        ),
        migrations.AddField(
            model_name='travel',
            name='trip_member',
            field=models.ManyToManyField(related_name='joined_trip', to='travel_buddy_app.User'),
        ),
        migrations.AlterField(
            model_name='travel',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_trip', to='travel_buddy_app.User'),
        ),
    ]
